// alpha-numeric

export const A = 'a'
export const B = 'b'
export const C = 'c'
export const D = 'd'
export const E = 'e'
export const F = 'f'
export const G = 'g'
export const H = 'h'
export const I = 'i'
export const J = 'j'
export const K = 'k'
export const L = 'l'
export const M = 'm'
export const N = 'n'
export const O = 'o'
export const P = 'p'
export const Q = 'q'
export const R = 'r'
export const S = 's'
export const T = 't'
export const U = 'u'
export const V = 'v'
export const W = 'w'
export const X = 'x'
export const Y = 'y'
export const Z = 'z'

export const NUM_0 = '0'
export const NUM_1 = '1'
export const NUM_2 = '2'
export const NUM_3 = '3'
export const NUM_4 = '4'
export const NUM_5 = '5'
export const NUM_6 = '6'
export const NUM_7 = '7'
export const NUM_8 = '8'
export const NUM_9 = '9'

// modifier

export const ALT         = 'Alt'
export const ALT_GRAPH   = 'AltGraph'
export const CAPS_LOCK   = 'CapsLock'
export const CONTROL     = 'Control'
export const CTRL        = 'Control'
export const FN          = 'Fn'
export const FN_LOCK     = 'FnLock'
export const HYPER       = 'Hyper'
export const META        = 'Meta'
export const NUM_LOCK    = 'NumLock'
export const SCROLL_LOCK = 'ScrollLock'
export const SHIFT       = 'Shift'
export const SUPER       = 'Super'
export const SYMBOL      = 'Symbol'
export const SYMBOL_LOCK = 'SymbolLock'

// whitespace 

export const ENTER = 'Enter'
export const SPACE = ' '
export const TAB   = 'Tab'

// navigation

export const ARROW_DOWN  = 'ArrowDown'
export const ARROW_LEFT  = 'ArrowLeft'
export const ARROW_RIGHT = 'ArrowRight'
export const ARROW_UP    = 'ArrowUp'
export const END         = 'End'
export const HOME        = 'Home'
export const PAGE_DOWN   = 'PageDown'
export const PAGE_UP     = 'PageUp'

// editing

export const BACKSPACE = 'Backspace'
export const CLEAR     = 'Clear'
export const COPY      = 'Copy'
export const CR_SEL    = 'CrSel'
export const CUT       = 'Cut'
export const DEL       = 'Delete'
export const DELETE    = 'Delete'
export const EX_SEL    = 'ExSel'
export const INS       = 'Insert'
export const INSERT    = 'Insert'

// ui

export const ACCEPT       = 'Accept'
export const AGAIN        = 'Again'
export const ATTN         = 'Attn'
export const CANCEL       = 'Cancel'
export const CONTEXT_MENU = 'ContextMenu'
export const ESC          = 'Escape'
export const ESCAPE       = 'Escape'
export const EXEC         = 'Execute'
export const EXECUTE      = 'Execute'
export const FIND         = 'Find'
export const FINISH       = 'Finish'
export const HELP         = 'Help'
export const PAUSE        = 'Pause'
export const PLAY         = 'Play'
export const PROPS        = 'Props'
export const SELECT       = 'Select'
export const ZOOM_IN      = 'ZoomIn'
export const ZOOM_OUT     = 'ZoomOut'

// functions

export const F1    = 'F1'
export const F2    = 'F2'
export const F3    = 'F3'
export const F4    = 'F4'
export const F5    = 'F5'
export const F6    = 'F6'
export const F7    = 'F7'
export const F8    = 'F8'
export const F9    = 'F9'
export const F10   = 'F10'
export const F11   = 'F11'
export const F12   = 'F12'
export const F13   = 'F13'
export const F14   = 'F14'
export const F15   = 'F15'
export const F16   = 'F16'
export const F17   = 'F17'
export const F18   = 'F18'
export const F19   = 'F19'
export const F20   = 'F20'
export const SOFT1 = 'Soft1'
export const SOFT2 = 'Soft1'
export const SOFT3 = 'Soft1'
export const SOFT4 = 'Soft1'
